language: node_js
node_js:
  - "8"
  - "9"
  - "10"
env:
  matrix:
  - TEST_SUITE=build
cache:
  directories:
  - node_modules
script:
- npm run build
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
